config/routes.rb
Rails.application.routes.draw do
  get 'info/kadai(.:format)'
  
  root to: 'static_pages#home'
  get    'signup', to: 'users#new'
  get    'login' , to: 'sessions#new'
  post   'login' , to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users do
    member do
      get 'followings'
      get 'followers'
    end
  end
  
  resources :microposts
  resources :relationships, only: [:create, :destroy]
  resources :info
  
   resources :events do
    member do
      post "add", to: "clips#create"
    end
  end

  resources :clips, only: [:destroy]
end

app/models/user.rb
class User < ActiveRecord::Base
paginates_per 50
max_paginates_per 50

  before_save { self.email = self.email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :area, presence: true, length: { maximum: 50 } 
  validates :profile, presence: true, length: { maximum: 200 } 
  has_many :microposts
  has_secure_password
  
  #フォロー
   has_many :follower_relationships, class_name:  "Relationship",
                                    foreign_key: "followed_id",
                                    dependent:   :destroy
  
  has_many :follower_users, through: :follower_relationships, source: :follower
  
  has_many :following_relationships, class_name:  "Relationship",
                                     foreign_key: "follower_id",
                                     dependent:   :destroy
                                     
  has_many :following_users, through: :following_relationships, source: :followed
  
   # 他のユーザーをフォローする
  def follow(other_user)
    following_relationships.find_or_create_by(followed_id: other_user.id)
  end

  # フォローしているユーザーをアンフォローする
  def unfollow(other_user)
    following_relationship = following_relationships.find_by(followed_id: other_user.id)
    following_relationship.destroy if following_relationship
  end

  # あるユーザーをフォローしているかどうか？
  def following?(other_user)
    following_users.include?(other_user)
  end
  
  # 10.1 タイムラインを取得するメソッドの追加
   def feed_items
    Micropost.where(user_id: following_user_ids + [self.id])
  end
end

app/controllers/users_controller.rb
   class UsersController < ApplicationController
  before_action :correct_user, only: [:edit, :update]

  def new
    @user = User.new
  end
  
   def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.order(created_at: :desc).page(params[:page])
  end
  
 def edit
  @user = User.find(params[:id])
end

 def update
  @user = User.find(params[:id])
   if  @user.update(user_params)
      # 保存に成功した場合はトップページへリダイレクト
      redirect_to root_path 
      flash[:success] = "プロフィールを更新しました"
    else
      # 保存に失敗した場合は編集画面へ戻す
      render 'edit'
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "ログインされました"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  
  def followings
      @user = User.find(params[:id])
      @followings = @user.following_users
  end
  
  def followers
    @user = User.find(params[:id])
    @followers = @user.follower_users
  end
  
    private
    
    def user_params
      params.require(:user).permit(:name, :email, :password,:password_confirmation,:area,:profile)
    end
    
    def correct_user
     @user = User.find(params[:id])
        redirect_to(root_path) unless @user == current_user 
   end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
   
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>
  

app/views/users/_follow_form.html.erb
<% if current_user != @user %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/edit.html.erb
<h1>
  <%= gravatar_for @user %>
  <%= @user.name %>
</h1>
<h2>プロフィールを編集する(editページのセッティングス）</h2>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %> <!-- ここを追加 -->

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      
      <%= f.label :area %>
      <%= f.text_field :area, class: 'form-control' %>
      
      <%= f.label :profile %>
      <%= f.text_field :profile, class: 'form-control' %>
      
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "内容を更新する", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/followers.html.erb
<h1 class="followingfolower">followers list</h1>
<h2>user/followers.html.erb</h2>
<li><%= link_to "UserProfile", current_user %></li>
<div class="col-xs-6 col-sm-push-3">
　<div class="panel panel-default">
  　<div class="panel-heading">現在、あなたをフォローされてる人です</div>
      <table class="table table-hover">
       <tbody>
    	　　<tr>
    	　　　<th>写真</th>
    	　　　<th>名前</th>
    	　　</tr>
    	　　　<tr>
    	　　　<% @followers.each do |user| %>
        		<td><%= gravatar_for(user) %></td>
        		<td><%= user.name %></td>
        	</tr>
 　　　　　　<% end %>
    	</tbody>
  　</table>
   </div>
</div>

app/views/users/followings.html.erb
<h1 class="followfollower">followings user lists</h1>
<h2>user/followings.html.erb</h2>

<div class="col-xs-6 col-sm-push-3">
　<div class="panel panel-default">
  　<div class="panel-heading">現在、あなたがフォローしてる人です</div>
  　　<table class="table table-hover">
       <tbody>
    	　　<tr>
    	　　　<th>写真</th>
    	　　　<th>名前</th>
    	　　</tr>
    	　　　<tr>
    	　　　<% @followings.each do |user| %>
    		<td><%= gravatar_for(user) %></td>
    		<td><%= user.name %></td>
    		</tr>
 　　　　　　<% end %>
    	</tbody>
  　</table>
　</div>
</div>

app/views/users/kadai.html.erb
<%= render 'info/kadai' %>
<h2>レッスン７　課題：オリジナル機能追加とHerokuへのデプロイ</h2>
<div class="panel panel-default">
  <div class="panel-heading">（製作条件）<a href="https://git.heroku.com/safe-tor-23114.git">Heroku上のWebアプリケーションにアクセスする</a></div>
</div>
<table class="table table-bordered">
	<tbody>
		<tr>
			<th  class="success">番号</th>
			<th  class="success">内容</th>
			<th  class="success">コマンド/備考</th>
		</tr>
		<tr>
			<td>１</td>
			<td>ここまで出来たら動作確認し、新しいブランチを作成（名前は、microposts-heroku）</td>
			<td>git checkout -b microposts-heroku</td>
		</tr>
		<tr>
			<td>2</td>
			<td>micropostsに、オリジナルのmicropostsにない機能を追加してカスタマイズしてください。<br>
			    カスタマイズの内容はデザインだけなく、Rubyのコードが必要な、独自性のある機能追加が好ましい</td>
			<td>この後のチャプターの「拡張してみよう」を参考</td>
		</tr>
		<tr>
			<td>3</td>
			<td>カスタマイズしたアプリケーションをHerokuにアップロードして動かしてください。</td>
			<td>動かし方はメッセージボードのレッスンなどを参考</td>
		</tr>
		<tr>
			<td>3</td>
			<td>完成したらGitHubにブランチをプッシュ</td>
			<td>git init<br>git commit -m "first commit"<br>git remote add origin https://github.com/yukaumemura/microposts.git</td>
		</tr>
		<tr>
			<td>4</td>
			<td>リポジトリ名(microposts)とブランチ名(microposts-heroku)を選択</td>
			<td>git push microposts microposts-heroku<br>yukaumemura</td>
		</tr>
		<tr>
			<td>5</td>
			<td>コメントに必ずアプリケーションHerokuのURLと実装したオリジナル機能の内容を記載提出</td>
			<td> 必ずアプリケーションのHerokuURLにアクセスして、オリジナル機能の動作確認</td>
		</tr>
		<tr>
			<td>6</td>
			<td>課題提出後はmasterブランチに戻って作業を行ってください。</td>
			<td>git checkout microposts-heroku<br>git merge master</td>
		</tr>
		<tr>
			<td>7</td>
			<td>(提出時の注意)提出フォームの項目にある「動作確認用URL」には「HerokuのURL」を記載</td>
			<td></td>
		<tr>
			<td>8</td>
			<td>コードレビュー合格後にmicroposts-herokuブランチをmasterブランチにマージ</td>
			<td></td>
		</tr>
	</tbody>
</table>

app/views/users/new.html.erb
<h1>Sign up</h1>
<h2>ご登録したいアカウントをご記入とご確認の上でアカウント登録確認を押して下さい</h2>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %> <!-- ここを追加 -->

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      
      <%= f.label :area %>
      <%= f.text_field :area, class: 'form-control' %>
      
      <%= f.label :profile %>
      <%= f.text_field :profile, class: 'form-control' %>
      
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "アカウント登録確認", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<P>users/show.erb</P>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
    　　<ol class="breadcrumb">
        <li><%= link_to "ツイート", @user %></li>
        <li><%= link_to "フォロー", followings_user_path(@user) %></li>
        <li><%= link_to "フォロワー", followers_user_path(@user) %></li>
      </ol>
  </aside>
  <div class="col-md-8">
    <%= render 'follow_form' if logged_in? %>
    <% if @user.microposts.any? %>
      <h3>Microposts (<%= @user.microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
    <% end %>
  </div>
</div>
<%= paginate @microposts %>

app/views/users/users.html.erb
<h1>
  <%= gravatar_for @user %>
  <%= @user.name %>
</h1>
<h2>プロフィールを編集する(editページのセッティングス）</h2>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %> <!-- ここを追加 -->

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      
      <%= f.label :area %>
      <%= f.text_field :area, class: 'form-control' %>
      
      <%= f.label :profile %>
      <%= f.text_field :profile, class: 'form-control' %>
      
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "内容を更新する", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>